import type { Product, Category, Order } from './types';
import { Coffee, Croissant, Pizza, Sandwich, GlassWater } from 'lucide-react';

export const categories: Category[] = [
  { id: 'bebidas-calientes', name: 'Bebidas Calientes', icon: Coffee },
  { id: 'desayunos', name: 'Desayunos', icon: Croissant },
  { id: 'bebidas-frias', name: 'Bebidas Frías', icon: GlassWater },
  { id: 'postres', name: 'Postres', icon: Pizza },
  { id: 'snacks', name: 'Snacks', icon: Sandwich },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'espresso-americano',
    name: 'Espresso Americano',
    description: 'Café espresso diluido con agua caliente, de sabor intenso y cuerpo ligero. Perfecto para empezar el día con energía.',
    category: 'bebidas-calientes',
    imageId: 'espresso-americano',
    sizes: [
      { name: 'Chico', price: 45.00, available: true },
      { name: 'Mediano', price: 55.00, available: true },
      { name: 'Grande', price: 65.00, available: true },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '2',
    slug: 'cappuccino-italiano',
    name: 'Cappuccino Italiano',
    description: 'El clásico italiano con un shot de espresso, leche vaporizada y una generosa capa de espuma de leche. Decorado con cacao en polvo.',
    category: 'bebidas-calientes',
    imageId: 'cappuccino-italiano',
    sizes: [
      { name: 'Chico', price: 50.00, available: true },
      { name: 'Mediano', price: 60.00, available: true },
      { name: 'Grande', price: 80.00, available: true },
    ],
    available: true,
    promotion2x1: true,
  },
  {
    id: '3',
    slug: 'latte-vainilla',
    name: 'Latte Vainilla',
    description: 'Suave y cremoso, este latte combina espresso con leche vaporizada y un toque dulce de sirope de vainilla.',
    category: 'bebidas-calientes',
    imageId: 'latte-vainilla',
    sizes: [
      { name: 'Chico', price: 40.00, available: false },
      { name: 'Mediano', price: 60.00, available: true },
      { name: 'Grande', price: 80.00, available: true },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '4',
    slug: 'croissant-mantequilla',
    name: 'Croissant de Mantequilla',
    description: 'Hojaldrado, tierno y con un intenso sabor a mantequilla. Recién horneado cada mañana para una experiencia perfecta.',
    category: 'desayunos',
    imageId: 'croissant-mantequilla',
    sizes: [
      { name: 'Chico', price: 35.00, available: true },
      { name: 'Mediano', price: 40.00, available: false },
      { name: 'Grande', price: 45.00, available: false },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '5',
    slug: 'tostada-aguacate',
    name: 'Tostada de Aguacate',
    description: 'Pan artesanal tostado, cubierto con aguacate fresco, un toque de limón, sal marina y hojuelas de chile.',
    category: 'desayunos',
    imageId: 'tostada-aguacate',
    sizes: [
      { name: 'Chico', price: 65.00, available: true },
      { name: 'Mediano', price: 75.00, available: false },
      { name: 'Grande', price: 95.00, available: false },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '6',
    slug: 'frappe-caramelo',
    name: 'Frappé de Caramelo',
    description: 'Una bebida refrescante y dulce, hecha con café, leche, hielo y sirope de caramelo, coronada con crema batida.',
    category: 'bebidas-frias',
    imageId: 'frappe-caramelo',
    sizes: [
      { name: 'Mediano', price: 40.00, available: true },
      { name: 'Grande', price: 50.00, available: true },
      { name: 'Chico', price: 60.00, available: false },
    ],
    available: true,
    promotion2x1: true,
  },
  {
    id: '7',
    slug: 'te-helado-limon',
    name: 'Té Helado de Limón',
    description: 'Té negro helado con un toque cítrico de limón fresco. La bebida perfecta para un día caluroso.',
    category: 'bebidas-frias',
    imageId: 'te-helado-limon',
    sizes: [
      { name: 'Mediano', price: 35.00, available: true },
      { name: 'Grande', price: 45.00, available: true },
      { name: 'Chico', price: 55.00, available: true },
    ],
    available: false,
    promotion2x1: false,
  },
  {
    id: '8',
    slug: 'cheesecake-fresa',
    name: 'Cheesecake de Fresa',
    description: 'Cremoso cheesecake sobre una base de galleta, cubierto con una generosa capa de mermelada de fresa casera.',
    category: 'postres',
    imageId: 'cheesecake-fresa',
    sizes: [
      { name: 'Chico', price: 4.50, available: true },
      { name: 'Mediano', price: 4.50, available: false },
      { name: 'Grande', price: 4.50, available: false },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '9',
    slug: 'muffin-chocolate',
    name: 'Muffin de Chocolate',
    description: 'Esponjoso y lleno de trozos de chocolate, nuestro muffin es el acompañamiento ideal para tu café.',
    category: 'postres',
    imageId: 'muffin-chocolate',
    sizes: [
      { name: 'Chico', price: 30.00, available: true },
      { name: 'Mediano', price: 35.00, available: false },
      { name: 'Grande', price: 40.00, available: false },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '10',
    slug: 'sandwich-pavo',
    name: 'Sandwich de Pavo',
    description: 'Pan integral con lonchas de pavo, queso suizo, lechuga, tomate y una mayonesa ligera de hierbas.',
    category: 'snacks',
    imageId: 'sandwich-pavo',
    sizes: [
      { name: 'Chico', price: 65.00, available: true },
      { name: 'Mediano', price: 75.00, available: false },
      { name: 'Grande', price: 85.00, available: false },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '11',
    slug: 'papas-fritas-artesanales',
    name: 'Papas Fritas Artesanales',
    description: 'Papas cortadas a mano y fritas a la perfección, servidas con tu elección de salsa de la casa.',
    category: 'snacks',
    imageId: 'papas-fritas-artesanales',
    sizes: [
      { name: 'Chico', price: 35.00, available: true },
      { name: 'Mediano', price: 45.00, available: false },
      { name: 'Grande', price: 55.00, available: false },
    ],
    available: true,
    promotion2x1: false,
  },
  {
    id: '12',
    slug: 'focaccia-italiana',
    name: 'Focaccia Italiana',
    description: 'Una delicia para desayunar traida desde el mismo itali, deliciosas rebanadas de salami con queso mozarella y ricota, acompañado de una salsa pesto',
    category: 'desayunos',
    imageId: 'focaccia-italiana',
    sizes: [
      { name: 'Mediano', price: 80.00, available: true },
      { name: 'Grande', price: 100.00, available: true },
    ],
    available: true,
    promotion2x1: false,
  },
];

export const orders: Order[] = [
  {
    id: 'GS-20231119-0001',
    customerName: 'Juan Pérez',
    customerPhone: '555-1234',
    items: [
      { id: '2-Grande', productId: '2', productName: 'Cappuccino Italiano', productImageId: 'cappuccino-italiano', size: 'Grande', quantity: 2, unitPrice: 4.00, promotion2x1: true },
      { id: '4-Chico', productId: '4', productName: 'Croissant de Mantequilla', productImageId: 'croissant-mantequilla', size: 'Chico', quantity: 1, unitPrice: 2.00, promotion2x1: false },
    ],
    subtotal: 10.00,
    discounts: 4.00,
    total: 6.00,
    paymentMethod: 'tarjeta',
    status: 'en_preparacion',
    estimatedTime: 7200,
    timestamps: {
      recibido: Date.now() - 5 * 60 * 1000,
      en_preparacion: Date.now() - 2 * 60 * 1000,
    },
  },
];
